<div class="cp-app-container" data-app="tags" data-page="1">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                Tags
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage site tags
                    </h2>
                </div>
                <div class="body">
                    <div class="row mb-3">
                        <div class="col-lg-6 col-md-8 col-sm-12 mb-2 mb-lg-0">
                            <div class="input-group">
                                <input type="text" class="form-control" id="new-tag-name" placeholder="Enter tag name">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="button" data-an="add-tag-btn">
                                        Add tag
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-4 col-sm-12">
                            <div class="input-group">
                                <input type="text" class="form-control" id="search-tag-name" placeholder="Search tags">
                                <div class="input-group-append">
                                    <button class="btn btn-secondary" type="button" data-an="search-tag-btn">
                                        Search
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tag</th>
                                    <th>Posts</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody data-an="tags-list">
                                <?php if (not_empty($cl['tags'])): ?>
                                    <?php foreach ($cl['tags'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/tags/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="5">
                                            <div class="empty-table">
                                                <h4>
                                                    No tags found
                                                </h4>
                                                <p>
                                                    It looks like there are no tags in your database yet. All tags used on your site will be displayed here.
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <?php if (not_empty($cl['tags'])): ?>
                                <a data-an="pagination" data-dir="prev" href="javascript:void(0);" class="pagination-ctrls prev">
                                    <?php echo cl_ficon("arrow_left"); ?>
                                </a>
                                <a data-an="pagination" data-dir="next" href="javascript:void(0);" class="pagination-ctrls next">
                                    <?php echo cl_ficon("arrow_right"); ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/tags/scripts/app_master_script'); ?>
